# Generated by Django 3.2.23 on 2024-03-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinApp', '0003_alter_post_tags'),
        ('BulletinApp', '0003_auto_20240301_2116'),
    ]

    operations = [
    ]
